- id: '1621084692233'
  alias: Turn Off Downtairs
  description: ''
  trigger:
  - platform: time
    at: '21:30:00'
  condition:
  - condition: device
    type: is_on
    device_id: 6e0e76eb8cf2734e4c2cd560c315df8a
    entity_id: switch.downstairs_switch
    domain: switch
  action:
  - type: turn_off
    device_id: 6e0e76eb8cf2734e4c2cd560c315df8a
    entity_id: switch.downstairs_switch
    domain: switch
  mode: single
- id: '1621085068348'
  alias: Turn Off Upstairs
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{%- if not is_state("alarm_control_panel.home", "armed_away")
        -%} true {%- endif -%}'
    - condition: device
      type: is_on
      device_id: 40c1c970e5fd7a6f9d55f3c746585dcd
      entity_id: switch.in_wall_toggle_switch
      domain: switch
  action:
  - type: turn_off
    device_id: 40c1c970e5fd7a6f9d55f3c746585dcd
    entity_id: switch.in_wall_toggle_switch
    domain: switch
  mode: single
- id: '1621086249993'
  alias: Turn Off Front Door At 4 am
  description: ''
  trigger:
  - platform: time
    at: 04:00
  condition:
  - condition: device
    type: is_on
    device_id: 1e38ac225e29516a04a53f7e48408c01
    entity_id: switch.in_wall_toggle_switch_2
    domain: switch
  action:
  - type: turn_off
    device_id: 1e38ac225e29516a04a53f7e48408c01
    entity_id: switch.in_wall_toggle_switch_2
    domain: switch
  mode: single
- id: '1625793522989'
  alias: Turn On Front Door
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '0.0'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '15:00:00'
      before: '21:50:00'
    - condition: state
      entity_id: switch.in_wall_toggle_switch_2
      state: 'off'
  action:
  - type: turn_on
    device_id: 1e38ac225e29516a04a53f7e48408c01
    entity_id: switch.in_wall_toggle_switch_2
    domain: switch
  mode: single
- id: '1637633079816'
  alias: Turn Off Front Door
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: state
    entity_id: switch.in_wall_toggle_switch_2
    state: 'on'
  action:
  - type: turn_off
    device_id: 1e38ac225e29516a04a53f7e48408c01
    entity_id: switch.in_wall_toggle_switch_2
    domain: switch
  mode: single
- id: '1653859128582'
  alias: Turn On Upstairs
  description: ''
  trigger:
  - type: illuminance
    platform: device
    device_id: 0b4424117600867dabbb872eb09ab0d4
    entity_id: sensor.multisensor_6_illuminance
    domain: sensor
    below: 5
  condition:
  - condition: and
    conditions:
    - condition: time
      after: 09:00:00
      before: '21:00:00'
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
    - condition: device
      type: is_off
      device_id: 40c1c970e5fd7a6f9d55f3c746585dcd
      entity_id: switch.in_wall_toggle_switch
      domain: switch
  action:
  - type: turn_on
    device_id: 40c1c970e5fd7a6f9d55f3c746585dcd
    entity_id: switch.in_wall_toggle_switch
    domain: switch
  mode: single
- id: '1662812027746'
  alias: Friday 3 AM Backup
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.friday_3am
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: backup.create
    data: {}
  mode: single
- id: '1666450359739'
  alias: Notify Twilio Dryer Leak
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.flood_freeze_behind_dryer_sensor_state_water
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.twilio
    data:
      message: There is a leak near the dryer
      target:
      - '+16147834965'
      - '+16147871065'
  - service: notify.mobile_app_pixel_6_mike
    data:
      message: There is a leak near the dryer
      title: There is a leak near the dryer
  mode: single
- id: '1666450409048'
  alias: Notify Twilio Water Heater Leak
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.flood_freeze_water_heater_sensor_state_water
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.twilio
    data:
      message: There is a leak near the water heater
      target:
      - '+16147834965'
      - '+16147871065'
  - service: notify.mobile_app_pixel_6_mike
    data:
      message: There is a leak near the water heater
      title: There is a leak near the water heater
  mode: single
- id: '1684532243377'
  alias: Notify Discord Dryer Leak
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.flood_freeze_behind_dryer_sensor_state_water
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.homeassistantcord
    data:
      message: <@509490668020957195> <@336671985453105152> There is a leak near the
        dryer
      target:
      - '1109083323659202666'
  - service: notify.mobile_app_pixel_6_mike
    data:
      message: There is a leak near the dryer
      title: There is a leak near the dryer
  mode: single
- id: '1684532416275'
  alias: Notify Discord Water Heater Leak
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.flood_freeze_water_heater_sensor_state_water
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.homeassistantcord
    data:
      message: <@509490668020957195> <@336671985453105152> There is a leak near the
        water heater
      target:
      - '1109083323659202666'
  - service: notify.mobile_app_pixel_6_mike
    data:
      message: There is a leak near the water heater
      title: There is a leak near the water heater
  mode: single
- id: '1686615431510'
  alias: Turn On Downstairs
  description: ''
  trigger:
  - type: illuminance
    platform: device
    device_id: d10e6c0d67b3efa07bcd7fc8a0bb5d5a
    entity_id: sensor.multisensor_6_illuminance_2
    domain: sensor
    below: 5
  condition:
  - condition: and
    conditions:
    - condition: time
      after: 09:00:00
      before: '20:30:00'
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
    - condition: state
      entity_id: switch.downstairs_switch
      state: 'off'
  action:
  - type: turn_on
    device_id: 6e0e76eb8cf2734e4c2cd560c315df8a
    entity_id: switch.downstairs_switch
    domain: switch
  mode: single
- id: '1687220781344'
  alias: Notify Test App Mike
  description: ''
  trigger:
  - platform: time
    at: '11:37:00'
  condition: []
  action:
  - service: notify.mobile_app_pixel_6_mike
    data:
      message: msg 2
      title: test tite 2
      target:
      - notify.mobile_app_pixel_6_mike
  mode: single
- id: '1687361480935'
  alias: Notify Test App Steph
  description: ''
  trigger:
  - platform: time
    at: '11:36:00'
  condition: []
  action:
  - service: notify.mobile_app_pixel_6_steph
    data:
      message: test message
      title: test title
      target:
      - notify.mobile_app_pixel_6_steph
  mode: single
- id: '1687559017914'
  alias: Notify All Phones Doorbell
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      notify_group: frigate_phones
      camera: camera.doorbell
      critical: 'true'
      zone_filter: true
      base_url: NABU_CASA_URL
      zones:
      - doorbell_front_door
- id: '1687559556435'
  alias: Notify All Phone Driveway
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      notify_group: frigate_phones
      camera: camera.floodlight
      critical: 'true'
      zone_filter: true
      base_url: NABU_CASA_URL
      zones:
      - flood_enter_driveway
- id: '1687560198684'
  alias: 'Notify Steph Doorbell '
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.doorbell
      notify_device: d7b9b30b1031aa25747347c259424903
      base_url: NABU_CASA_URL
      critical: 'true'
      zone_filter: true
      zones:
      - doorbell_front_door
- id: '1687560273071'
  alias: Notify Steph Driveway
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.floodlight
      base_url: NABU_CASA_URL
      critical: 'true'
      zone_filter: true
      zones:
      - flood_enter_driveway
      disable_times:
      - '0'
      - '2'
      - '1'
      - '3'
      - '4'
      - '22'
      - '23'
      - '21'
      update_thumbnail: false
      notify_device: d7b9b30b1031aa25747347c259424903
- id: '1687560305577'
  alias: Notify Mike Driveway
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.floodlight
      base_url: NABU_CASA_URL
      critical: 'true'
      zone_filter: true
      zones:
      - flood_enter_driveway
      color: steelblue
      disable_times:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '23'
      - '22'
      - '21'
      update_thumbnail: false
      debug: false
      notify_device: 55e6c7bc2e63b0dd8d479cb62e349d47
- id: '1687560324140'
  alias: Notify Mike Doorbell
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.doorbell
      notify_device: 55e6c7bc2e63b0dd8d479cb62e349d47
      base_url: NABU_CASA_URL
      critical: 'true'
      zone_filter: true
      zones:
      - doorbell_front_door
      color: steelblue
      debug: false
- id: '1687562390747'
  alias: Notify Doorbell Pushed
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 53f541e078dd8bce4b8fe9773b61862c
    entity_id: binary_sensor.reolink_video_doorbell_wifi_visitor
    domain: binary_sensor
  condition: []
  action:
  - service: notify.frigate_phones
    data:
      message: Someone is at the door
      title: Knock Knock
      target:
      - nofity.frigate_phones
  mode: single
- id: '1688849445922'
  alias: Notify Mike Deck
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.deck
      notify_device: 55e6c7bc2e63b0dd8d479cb62e349d47
      base_url: NABU_CASA_URL
      critical: 'true'
- id: '1688849481628'
  alias: Notify Steph Deck
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.deck
      base_url: NABU_CASA_URL
      critical: 'true'
      notify_device: d7b9b30b1031aa25747347c259424903
- id: '1690458871116'
  alias: Notify Mike Reolink Port Broken
  description: ''
  trigger:
  - platform: mqtt
    topic: reolink/port_status
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json[''status''] == "broken" }}'
    enabled: true
  action:
  - service: notify.mobile_app_pixel_6_mike
    data_template:
      message: '{{ trigger.payload_json.camera }} ports broken'
      title: '{{ trigger.payload_json.camera }} ports broken'
      target:
      - notify.mobile_app_pixel_6_mike
  mode: single
- id: '1690588303502'
  alias: Notify Mike Test Stationary
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
  condition:
  - condition: template
    value_template: '{% if trigger.payload_json["after"]["stationary"] == false %}

      true

      {% else %}

      false

      {% endif %}'
  action:
  - service: notify.mobile_app_pixel_6_mike
    data:
      message: motion trigger
      title: motion trigger
      target:
      - notify.mobile_app_pixel_6_mike
  mode: single
